# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
            - name: Setup Node.js Express and MySQL
  # You may pin to the exact commit or the version.
  # uses: Sunwoo0110/IREM@68c45e879a46a0864ae9f15fd878f7f2a03fe991
  uses: Sunwoo0110/IREM@v1.2.1
  with:
    # project github repository url which you want to setup
    github-repo-url: # default is 
    # user id
    github-user-id: # default is 
    # user email
    github-user-email: # default is 
    # user PAT
    github-token: # default is 
          
